// src/components/Tiles/UnitTile.tsx
import { Recipe } from "@/models/Recipe";
import React, { useEffect } from "react";
import { TouchableOpacity, View } from "react-native";
import { Text } from "../Basic/Text";
import { StyleSheet } from 'react-native';
import { getColor } from "@/constants/Colors";
import { Spacing } from "@/constants/Sizes";
import { GenericTileProp } from "../Basic/Search/GenericTile";
import { Unit } from "@/models/Unit";

export interface UnitTileProps extends GenericTileProp<Unit> {
}

export default function UnitTile({ data, onPress }: UnitTileProps) {

    const [rotation , setRotation] = React.useState<number>(0);
    useEffect(() => {
        setRotation(randomRotation());
    }, []);

    function randomRotation(): number {
        const min = -2; // Minimum rotation in degrees
        const max = 2;  // Maximum rotation in degrees
        return Math.random() * (max - min) + min;
    }

//#region Styles
    const style = StyleSheet.create({
        container: {
            transform: [{ rotate: `${rotation}deg` }],
            backgroundColor: getColor('paper'),
            maxWidth: 200,
            gap: 5,
            elevation: 15,
            padding: Spacing.md
        },
        magnetContainer: {
            position: 'absolute',
            top: 4,
            left: '55%',
            width: 12,
            height: 12,
            borderRadius: 6,
            zIndex: 1,
            backgroundColor: getColor('magnet-shadow')
        },
        magnet: {
            position: 'relative',
            top: -2,
            width: '100%',
            height: '100%',
            borderRadius: 6,
            zIndex: 1,
            backgroundColor: getColor('magnet')
        }
    });
//#endregion
    return (
        <TouchableOpacity onPress={() => onPress && onPress(data.id)} activeOpacity={0.7} style = {[style.container]}>
                <View style={style.magnetContainer}>
                    <View style={style.magnet}/>
                </View>
                <Text 
                    content={data.name}            
                    type="subtitle"
                    variant="paper-prim"
                    mode="hand"
                />
                <Text 
                    content={`${data.volumeEquivalent} liters`}            
                    type="caption"
                    variant="paper-sec"
                    mode="hand"
                />
                <Text 
                    content={data.desc}            
                    type="caption"
                    variant="paper-sec"
                    mode="hand"
                />
        </TouchableOpacity>
    )
}

// src/components/Tiles/UnitTile.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import Text from '../Basic/Text.vue'
import type { Unit } from '@/models/Unit'
import type { GenericTileProp } from '../Basic/Search/GenericTile'
import './Tile.css'

interface UnitTileProps extends GenericTileProp<Unit> {}

const props = defineProps<UnitTileProps>()

const rotation = ref(0)

onMounted(() => {
  rotation.value = randomRotation()
})

function randomRotation(): number {
  const min = -2
  const max = 2
  return Math.random() * (max - min) + min
}

const handlePress = () => {
  if (props.onPress) {
    props.onPress(props.data)
  }
}

const handleMagnetPress = (event: MouseEvent) => {
  event.stopPropagation()
  if (props.onMagnetPress) {
    props.onMagnetPress(props.data)
  }
}
</script>

<template>
  <button class="tile" :style="{ transform: `rotate(${rotation}deg)` }" @click="handlePress">
    <div class="magnet-container">
      <div class="magnet" @click="handleMagnetPress" />
    </div>
    <Text :content="data.name" type="subtitle" variant="paper-prim" mode="hand" />
    <Text v-if="data.volumeEquivalent != null" :content="`${data.volumeEquivalent} l`" type="caption" variant="paper-sec" mode="hand" />
    <Text v-if="data.desc" :content="data.desc" type="caption" variant="paper-prim" mode="hand" />
  </button>
</template>
