// src/components/Forms/foodForm.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import Form from './Form.vue'
import Button from '@/components/Basic/Input/Button.vue'
import Input from '@/components/Basic/Input/Input.vue'
import Text from '@/components/Basic/Text.vue'
import ErrorMessage from '@/components/Basic/ErrorMessage.vue'
import LoadingIndicator from '@/components/Basic/LoadingIndicator.vue'
import SearchableDropdown, { type DropdownItem } from '@/components/Basic/Search/SearchableDropdown.vue'
import { foodService, type CreateFood, type Food, type UpdateFood } from '@/models/Food'
import { foodTypeService, type FoodType } from '@/models/FoodType'
import { DebouncTime } from '@/constants/Search'
import type { ValidationMessage } from '@/models/UtilityModels'
import type { GenericFormProp } from './GenericForm.ts'

interface FoodFormProps extends GenericFormProp<Food>{}

const props = withDefaults(defineProps<FoodFormProps>(), {
  data: () => ({ id: "", name: '', foodTypeId: '', foodType: { id: '', name: '' } })
})

type fieldTypes = 'name' | 'foodType'

const foodId = ref(props.data.id || "")
const currentFood = ref<Food>(props.data)
const isLoading = ref(false)
const isSaving = ref(false)
const errorMessage = ref('')
const validationMessages = ref<ValidationMessage<fieldTypes>[]>([])

// Food type search
const foodTypeItems = ref<DropdownItem<FoodType>[]>([])
const isFoodTypesLoading = ref(false)
const isAddingFoodType = ref(false)
const selectedFoodType = ref<DropdownItem<FoodType> | undefined>(undefined)

async function fetchFood() {
  console.log('Fetching food with ID:', foodId.value)
  if (isLoading.value) return
  isLoading.value = true
  const foodIdValue = foodId.value
  if (foodIdValue != "" && foodIdValue != null) {
    const food = await foodService.getById(foodIdValue)
    currentFood.value = food
    selectedFoodType.value = food.foodType && food.foodType.name !== ''
      ? { value: food.foodType, label: food.foodType.name }
      : undefined
  } else {
    currentFood.value = { id: "", name: '', foodTypeId: '', foodType: { id: '', name: '' } }
    selectedFoodType.value = undefined
  }
  isLoading.value = false
}

async function searchFoodTypes(query: string) {
  if (isFoodTypesLoading.value) return
  isFoodTypesLoading.value = true
  try {
    const response = await foodTypeService.getAll({ name: query, page: 1, perPage: 10 })
    foodTypeItems.value = response.map(t => ({ value: t, label: t.name }))
  } catch (error) {
    console.error('Failed to search food types:', error)
  }
  isFoodTypesLoading.value = false
}

onMounted(() => {
  fetchFood()
  searchFoodTypes('')
})

watch(() => props.data, (newData) => {
  console.log('Props data changed:', newData)
  foodId.value = newData.id || ""
  fetchFood()
}, { deep: true })

const onValueChange = (key: 'name', value: any) => {
  currentFood.value = { ...currentFood.value, [key]: value }
}

// Food type selection
const handleFoodTypeSelect = (item: DropdownItem) => {
  const foodType = item.value as FoodType
  selectedFoodType.value = { value: foodType, label: item.label }
  currentFood.value = { ...currentFood.value, foodTypeId: foodType.id, foodType: foodType }
}

// The dropdown's confirm (checkmark) action creates a new food type from the typed text
const handleAddFoodType = async (name: string) => {
  const trimmedName = name.trim()
  if (trimmedName === '' || isAddingFoodType.value) return

  const existing = foodTypeItems.value.find(i => i.label.toLowerCase() === trimmedName.toLowerCase())
  if (existing) {
    handleFoodTypeSelect(existing) // reuse the existing type instead of creating a duplicate
    return
  }

  isAddingFoodType.value = true
  errorMessage.value = ''
  try {
    const created = await foodTypeService.create({ name: trimmedName }) // POST /food_type
    const item: DropdownItem<FoodType> = { value: created, label: created.name }
    foodTypeItems.value = [item, ...foodTypeItems.value]
    handleFoodTypeSelect(item) // select the new type straight away
  } catch (error) {
    console.error('Failed to add food type:', error)
    errorMessage.value = 'Failed to add food type'
  }
  isAddingFoodType.value = false
}

// Validation
function validateFood(): boolean {
  const errors: ValidationMessage<fieldTypes>[] = []
  if (!currentFood.value.name || currentFood.value.name.trim() === '') {
    errors.push({ key: 'name', message: 'Food name is required' })
  }
  if (!currentFood.value.foodTypeId || currentFood.value.foodTypeId === '') {
    errors.push({ key: 'foodType', message: 'Food type is required' })
  }
  validationMessages.value = errors
  return errors.length === 0
}

const handleSave = async () => {
  if (isSaving.value) return
  isSaving.value = true
  errorMessage.value = ''

  try {
    if (!validateFood()) {
      errorMessage.value = 'Please fill in all required fields'
      return
    }

    if (currentFood.value.id != "" && currentFood.value.id != null) {
      const foodUpdateData: UpdateFood = {
        name: currentFood.value.name,
        foodTypeId: currentFood.value.foodTypeId,
      }
      await foodService.update(currentFood.value.id, foodUpdateData)
    } else {
      const foodCreateData: CreateFood = {
        name: currentFood.value.name,
        foodTypeId: currentFood.value.foodTypeId,
      }
      await foodService.create(foodCreateData)
    }
    props.onSubmit?.(currentFood.value)
  } catch (error) {
    errorMessage.value = 'Failed to save food'
    console.error('Save error:', error)
  } finally {
    isSaving.value = false
  }
}

function getValidationMessage(key: fieldTypes): string | null {
  const vm = validationMessages.value.find(v => v.key === key)
  if (vm == null || vm == undefined) {
    return null
  } else {
    return vm.message
  }
}
</script>

<template>
  <div v-if="isLoading">
    <LoadingIndicator />
  </div>
  <div v-else>
    <Form>
      <div class="section-container">
        <Text type="title" variant="prim-prim" content="Food" />

        <div class="input-container">
          <Text type="body" content="Food Name" />
          <Input
            :value="currentFood.name"
            placeholder="Food name"
            :onChangeText="(v: string) => onValueChange('name', v)"
            :disabled="isSaving"
            variant="paper"
          />
          <Text v-if="getValidationMessage('name')" type="caption" variant="warning" :content="getValidationMessage('name') || ''" />
        </div>

        <div class="input-container">
          <Text type="body" content="Food Type" />
          <SearchableDropdown
            placeholder="Search food type"
            :items="foodTypeItems"
            :onSearch="searchFoodTypes"
            :onSelect="handleFoodTypeSelect"
            :onConfirm="handleAddFoodType"
            :selectedValue="selectedFoodType"
            :debounceTime="DebouncTime.short"
            :isSearching="isFoodTypesLoading"
            :disabled="isSaving"
            inputStyle="paper"
          />
          <Text type="caption" variant="sec-sec" content="Type a new type name and press the checkmark to add it" />
          <Text v-if="getValidationMessage('foodType')" type="caption" variant="warning" :content="getValidationMessage('foodType') || ''" />
        </div>
      </div>

      <div class="button-container">
        <Button
          :label="isSaving ? 'Saving...' : 'Save Food'"
          :onPress="handleSave"
          :disabled="isSaving"
        />
      </div>
    </Form>
    <ErrorMessage :message="errorMessage" :visible="errorMessage !== ''" />
  </div>
</template>

<style scoped>
.section-container {
  display: flex;
  flex-direction: column;
  gap: var(--form-element-gap);
}

.input-container {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-sm);
}

.button-container {
  margin-top: var(--spacing-lg);
  padding-bottom: var(--spacing-xl);
}
</style>

// src/components/Forms/foodForm.tsx
import Button from '@/components/Basic/Button'
import Input from '@/components/Basic/Input'
import { Text } from '@/components/Basic/Text'
import { Messages } from '@/constants/Messages'
import { Spacing } from '@/constants/Sizes'
import { ValidationMessage } from '@/models/UtilityModels'
import { useEffect, useState } from 'react'
import { StyleSheet, View } from 'react-native'
import { CreateFood, Food, foodService, UpdateFood } from '../../../models/Food'
import { FoodType, foodTypeService } from '../../../models/FoodType'
import ErrorMessage from '../../Basic/ErrorMessage'
import LoadingIndicator from '../../Basic/LoadingIndicator'
import SearchableDropdown, { DropdownItem } from '../../Basic/SearchableDropdown'
import { Form, FormContentProps, formStyle } from './form'
import { getColor } from '@/constants/Colors'

type fieldTypes = "name" | "foodTypeId" | "foodType"

export interface FoodFormProps extends FormContentProps {
    id?: string;
}

export default function FoodForm(params: FoodFormProps) {
    const foodId:string = params.id || 0;
    const [currentFood, setCurrentFood] = useState<Food>({} as Food);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [isSaving, setIsSaving] = useState<boolean>(false);
    const [errorMessage, setErrorMessage] = useState<string>("");
    const [validationMessages, setValidationMessages] = useState<ValidationMessage<fieldTypes>[]>([]);
    const [foodTypes, setFoodTypes] = useState<FoodType[]>([]);
    const [isFoodTypesLoading, setIsFoodTypesLoading] = useState<boolean>(false);
    const [foodTypeSearchError, setTypeSearchError]= useState<string>("");

    async function fetchFood() {
        if (isLoading) {
            return
        }
        setIsLoading(true)
        const foodIdNum = Number(foodId)
        if (foodIdNum > 0) {
            const food = await foodService.getById(foodIdNum)
            setCurrentFood(food)
        } else {
            const food: Food = {
                id: 0,
                name: "",
                foodTypeId: 0,
                foodType: {} as FoodType
            }
            setCurrentFood(food)
        }
        setIsLoading(false)
    }

    async function searchFoodTypes(query: string) {
        if (isFoodTypesLoading) {
            return
        }
        setIsFoodTypesLoading(true)
        try {
            const response = await foodTypeService.getAll({
                name: query,
                page: 1,
                perPage: 10
            });
            setFoodTypes(response);
        } catch (error) {
            setTypeSearchError(`${Messages.errorMessage} searching food types`)
        }
        setIsFoodTypesLoading(false)
    }

    useEffect(()=>{
        fetchFood();
    }, [foodId])

    const onValueChange = (key: fieldTypes, value: any) => {
        setCurrentFood(prev => ({ ...prev, [key]: value }))
    }

    const handleFoodTypeSelect = (item: DropdownItem<FoodType>) => {
        onValueChange('foodTypeId', item.value.id)
        onValueChange('foodType', item.value)
    }

    const handleAddType = async (typeName: string) => {
        console.log("Adding new food type:", typeName)
        try {
            const newType = await foodTypeService.create({ name: typeName })
            onValueChange('foodTypeId', newType.id)
            onValueChange('foodType', newType)
        } catch (error) {
            console.error('Failed to create food type:', error)
            setErrorMessage("Failed to create new food type")
        }
    }

    //#region data validation
    function validateUpdate(data: UpdateFood): boolean {
        const errors: ValidationMessage<fieldTypes>[] = []
        if (!data.name || data.name.trim() === "") {
            errors.push({ key: "name", message: "Food name is required" })
        }
        if (!data.foodTypeId || data.foodTypeId <= 0) {
            errors.push({ key: "foodTypeId", message: "Food type is required" })
        }

        setValidationMessages(errors)
        return errors.length === 0
    }

    function validateCreate(data: CreateFood): boolean {
        const errors: ValidationMessage<fieldTypes>[] = []
        if (!data.name || data.name.trim() === "") {
            errors.push({ key: "name", message: "Food name is required" })
        }
        if (!data.foodTypeId || data.foodTypeId <= 0) {
            errors.push({ key: "foodTypeId", message: "Food type is required" })
        }

        setValidationMessages(errors)
        return errors.length === 0
    }
    //#endregion

    const handleSave = async () => {
        if (isSaving) return
        
        setIsSaving(true)
        setErrorMessage("")

        try {
            if (currentFood.id > 0) {
                const foodUpdateData: UpdateFood = {
                    name: currentFood.name,
                    foodTypeId: currentFood.foodTypeId
                }
                if (validateUpdate(foodUpdateData)) {
                    await foodService.update(currentFood.id, foodUpdateData)
                } else {
                    setErrorMessage("Some required fields are not filled")
                }
            } else {
                const foodCreateData: CreateFood = {
                    name: currentFood.name,
                    foodTypeId: currentFood.foodTypeId
                }
                if (validateCreate(foodCreateData)) {
                    await foodService.create(foodCreateData)
                } else {
                    setErrorMessage("Some required fields are not filled")
                }
            }
        } catch (error) {
            setErrorMessage("Failed to save food item")
            console.error('Save error:', error)
        } finally {
            setIsSaving(false)
            params.onSubmit?.();
        }
    }

    function getValidationMessage(key: fieldTypes) {
        const vm = validationMessages.find(v => v.key === key)
        if (vm == null || vm == undefined) {
            return <></>
        } else {
            return (<Text type='caption' variant='warning' content={vm.message}/>)
        }
    }

    const foodTypeToDropdownItem = (items: FoodType[]): DropdownItem<FoodType>[] => {
        return items?.map(i => ({ value: i, label: i?.name })) || []
    }

    return (
        <>
            {isLoading ? (
                <LoadingIndicator/>
            ) : (
                <Form>
                    <View style={formStyle.sectionContainer}>
                        <Text type='title' variant='prim-prim' content='Food'/>
                                            
                        <Input 
                            value={currentFood.name} 
                            placeholder="Food name" 
                            onChangeText={(newText: string) => onValueChange('name', newText)}
                            variant='paper'
                        />
                        {getValidationMessage("name")}
                        
                        <View style={styles.inputContainer}>
                            <Text type='body' content='Food Type'/>
                            <SearchableDropdown<FoodType>
                                placeholder="Search food types..."
                                items={foodTypeToDropdownItem(foodTypes)}
                                onSearch={searchFoodTypes}
                                onSelect={handleFoodTypeSelect}
                                onConfirm={handleAddType}
                                selectedValue={currentFood.foodType ? foodTypeToDropdownItem([currentFood.foodType])[0] : undefined}
                                isSearching={isFoodTypesLoading}
                                errorMessage={foodTypeSearchError}
                                inputStyle='paper'
                            />
                        </View>
                        {getValidationMessage("foodTypeId")}
                        
                    </View>
                    <View style={formStyle.buttonContainer}>
                        <Button 
                            label={isSaving ? 'Saving...' : 'Save'} 
                            onPress={handleSave}
                            disabled={isSaving}
                        />
                    </View>
                </Form>
            )}
            <ErrorMessage message={errorMessage} visible={errorMessage !== ""}/>
            </>
    )
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    inputContainer: {
        gap: Spacing.sm,
        zIndex: 10
    }
})
